### ISSUE TITLE
Allow configuring contextPath for WebDriver

### ISSUE THREAD

**Issue by KyleRogers** [spring-projects/spring-test-htmlunit#40]
My application uses spring-boot and I'm not using any contextPath. I'm acceptance-testing my app with spring-test-htmlunit.

If I request `http://localhost/account/new` "`/account`" will be treated as contextPath and "`/new`" will be parsed as servlet path. This leads to wrong results. I could fake get requests with an additional path element but this doesn't work when submitting forms through HTMLUnit.

Next approach was extending `MockMvcHtmlUnitDriver` and overwriting `configureWebClient()`. I tried to create a new `MockMvcWebConnection` instance and set it in `WebClient`. `MockMvcWebConnection` provides a constructor that allows to set `contextPath` used. But this does not work either. The connection set in `configureWebClient()` will be overwritten in `setMockMvc()` called later.

Only thing I can do is patching spring-test-htmlunit.... I'll attach a pull request with the patch.

**Comment by BinaryTweedDeej** [comment]
I'd just like to add my voice to those that have been bitten by this one. I think default behaviour of expecting the SUT to be at the root context would uphold the principle of least astonishment best. Thanks for the workaround @KyleRogers

**Comment by rwinch** [comment]
>  I think default behaviour of expecting the SUT to be at the root context would uphold the principle of least astonishment best. 

I certainly agree we need to fix this issue.

I believe this really depends on if you deploy with or without a context root. I'm not sure I have any numbers on which (i.e. empty context root or having a context root) is more popular. I'm interested to hear any more arguments on what the default should be and open to changing the default.
