### ISSUE TITLE
Simple swap for other driver when using MockMvc?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-test-htmlunit#46]
If I have a failing test, it's often very helpful to review the screenshots that `GebReportingSpec` provides, but HtmlUnit just gives a DOM dump and no visuals. Is there any simple way to replace the HtmlUnit driver with PhantomJS or Chrome while still backing off the mock MVC instance, or would something like that require hooking into the network layer of the target browser?

**Comment by rwinch** [comment]
Thank you for your question. This project is for integration with HtmlUnit, so it is beyond the scope of the project to support any other WebDriver implementation. 

If you are interested in supporting other WebDriver implementations, then I'd suggest adding an enhancement request to http://jira.spring.io/browse/SPR

NOTE: This is not to say that I wouldn't like to support other implementations, but that I haven't had time to look into supporting other WebDriver implementations and we need to limit the scope to get this feature out the door. If you are inte
