### ISSUE TITLE
simpler DelegatingWebConnection configuration

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-test-htmlunit#55]
I have static resources pulled in from a number of sites (both company and public CDNs), and this appears to need a `DelegatingWebConnection`. It would be very helpful to (1) have a nice builder syntax where I can just pass a `String...` of matchers and the construction of the connection chain is taken care of, and (2) a simple way to say "everything but localhost".

I think it would make sense for (1) to live on the `MockMvcHtmlUnitDriverBuilder`, and if a simple not-regex will cover (2), it seems that canned builder method to that effect might be useful (I would be surprised if this scenario weren't extremely common these days with public hosting of jQuery, Bootstrap, and so on).

**Comment by rwinch** [comment]
By default `MockMvcHtmlUnitDriverBuilder` will only delegate requests to localhost to `MockMvc`. Can you simply ensure your main application uses localhost?

If not, you can add any number of hosts to be processed by MockMvc using [MockMvcHtmlUnitDriverBuilder.useMockMvcForHosts(String...)](https://github.com/spring-projects/spring-test-htmlunit/blob/1ff06572798367686af270e3481858df05ab7ca1/spring-test-htmlunit/src/main/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnectionBuilderSupport.java#L121).

NOTE: `MockMvcWebConnectionBuilderSupport` is the super class of `MockMvcHtmlUnitDriverBuilder`

Does this help?

**Comment by chrylis** [comment]
Hmm. I'll need to investigate then, because that's the setup I'm using, but I'm getting a JavaScript error that seems to indicate that RequireJS isn't being loaded from CDN:

    <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.15/require.min.js"></script>

**Comment by rwinch** [comment]
I assume you are using the latest SNAPSHOT?

**Comment by chrylis** [comment]
Never mind, I dumped via `GebReportingSpec`, and the HTML's not being formed properly, so the included script tag isn't the same one I'm seeing in a real launch. Looks to be an issue with `ThymeleafAutoConfiguration` and additional dialects.

**Comment by rwinch** [comment]
@chrylis  Thanks for getting back to me so fast and for all the feedback on the latest SNAPSHOTS!
