### ISSUE TITLE
MockMvc driver has no User-Agent

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-test-htmlunit#58]
I have some controllers that are inspecting the User-Agent header, and I got test failures when it wasn't present. While that needs to be optional anyway, it seems sensible to me that the HtmlUnit driver should set *something* for the header.

**Comment by rwinch** [comment]
Thank you for the feedback.

I don't think we should override headers that aren't explicitly set. If this is something that should be done, then it should likely be done in HtmlUnit itself.

If you want you can work around this using the default request for MockMvc. Something like:

```java
mockMvc = MockMvcBuilders
	.webAppContextSetup(wac)
	.defaultRequest(get("/").header("User-Agent", "HtmlUnit")).build();

// This is how you would do it with the code in spring-test
// (spring-test-htmlunit is now being maintained in spring-test going forward)
WebDriver driver = MockMvcHtmlUnitDriverBuilder.mockMvcSetup(mockMvc).build();

// This is how you would do it with the code in spring-test-htmlunit
WebDriver driver = MockMvcHtmlUnitDriverBuilder.mockMvcSetup(mockMvc).createDriver();
```
