### ISSUE TITLE
HtmlUnit 2.17 removed "CookieManager#getCookies()"

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-test-htmlunit#59]
The deprecated method `getCookies(URL)` was removed in 2.17, and spring-test-htmlunit will not run against it. The Javadoc indicates that `WebClient#getCookies(URL)` should be used instead.

**Comment by rwinch** [comment]
Thanks for the report. Spring Test HtmlUnit has been moved to spring-test and will be included in spring-test-4.2.0.RELEASE. This issue should be resolved in the code that was merged into spring-test. Please feel free to give it a try and provide feedback in https://jira.spring.io/browse/SPR
