### ISSUE TITLE
htmlunit-2.25 is not compatiable with sprint test framework now

### ISSUE THREAD

**Issue by workhours** [spring-projects/spring-test-htmlunit#64]
htmlunit-2.25 has changed return value of com.gargoylesoftware.htmlunit.WebRequest.getCharset() from String Type to Charset Type, this change break org.springframework.test.web.servlet.htmlunit.HtmlUnitRequestBuilder.getCharset() function

**Comment by rwinch** [comment]
Thanks for the report.

As per the [README](https://github.com/spring-projects/spring-test-htmlunit#spring-mvc-test-htmlunit) project is now integrated into Spring Framework's spring-test module and this project is no longer maintained
